version: '3'

services:
  mysql:
    image: mysql
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    # ports:
    #   - 3311:3306
    # volumes:
      #- ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_bsc
      MYSQL_DATABASE: leads
      MYSQL_PASSWORD: root_bsc
      MYSQL_USER: root_bsc
    networks:
      - mysql-development

networks:
  mysql-development: