version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql5.7_container
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql # map a local folder to keep data
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: database
      MYSQL_PASSWORD: root_pass
      MYSQL_USER: admin
    networks:
      - mysql-development

networks:
  mysql-development: